version: "3.8"

services:
    api:
        image: ${IMAGE_TAG}
        container_name: paybaba_api
        restart: always
        environment:
            NODE_ENV: production
            # Gunakan host.docker.internal untuk mengakses Postgres di server lokal
            DB_HOST: host.docker.internal
            DB_PORT: 5432
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            BASE_URL: ${BASE_URL}
            FRONTEND_URL: ${FRONTEND_URL}
            JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
            JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
            JWT_ACCESS_TOKEN_EXPIRY: ${JWT_ACCESS_TOKEN_EXPIRY}
            JWT_REFRESH_TOKEN_EXPIRY: ${JWT_REFRESH_TOKEN_EXPIRY}
            QWEN_API_KEY: ${QWEN_API_KEY}
            QWEN_BASE_URL: ${QWEN_BASE_URL}
            MID: ${MID}
            PRIVATE_KEY: ${PRIVATE_KEY}
            PUBLIC_KEY: ${PUBLIC_KEY}
            PAYLABS_SERVER: ${PAYLABS_SERVER}
            PAYLABS_BASE_URL: ${PAYLABS_BASE_URL}
            NOTIFY_URL: ${NOTIFY_URL}
        ports:
            # Terkoneksi ke Nginx di server
            - "127.0.0.1:3000:3000"
        extra_hosts:
            - "host.docker.internal:host-gateway" # WAJIB: Membuka jembatan ke IP server
        networks:
            - paybaba_network

networks:
    paybaba_network:
        driver: bridge
